version: "3.9"
services:
  db:
    image: postgres:14.3-alpine
    container_name: postgres
    restart: always
    ports:
      - published: ${POSTGRES_PORT:-6500}
        target: ${POSTGRES_PORT:-6500}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?error}
      POSTGRES_DB: ${POSTGRES_DB?error}
      POSTGRES_PORT: ${POSTGRES_PORT?error}
    expose:
      - ${POSTGRES_PORT:-6500}
    command:
      -p ${POSTGRES_PORT:-6500}
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - published: ${SERVER_PORT:-3000}
        target: ${SERVER_PORT:-3000}
    volumes:
      - .:/api/
    depends_on:
      - db
    environment:
      SERVER_PORT: ${SERVER_PORT?error}
      NODE_ENV: ${NODE_ENV?error}
volumes:
  db-data:
    driver: local
